# Generated by Django 4.1.2 on 2022-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=126)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=126)),
                ('city', models.CharField(max_length=126)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=11)),
                ('productid', models.IntegerField(max_length=10)),
                ('userid', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('payment_mode', models.IntegerField(max_length=2)),
                ('billdate', models.DateTimeField(auto_now_add=True)),
                ('pincode', models.IntegerField(max_length=8)),
                ('total', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('billid', models.IntegerField(max_length=10)),
                ('userid', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('image', models.CharField(max_length=256)),
                ('shopkeeperid', models.IntegerField(max_length=10)),
                ('blds', models.IntegerField(max_length=2)),
                ('isdeleted', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126)),
                ('price', models.IntegerField(max_length=10)),
                ('desc', models.TextField()),
                ('categoryid', models.IntegerField(max_length=10)),
                ('shopkeeperid', models.IntegerField(max_length=10)),
                ('image', models.CharField(max_length=256)),
                ('stock', models.IntegerField(max_length=2)),
                ('isdeleted', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='shopkeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=126)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('companyname', models.CharField(max_length=256)),
                ('mobilenum', models.IntegerField(max_length=256)),
                ('image', models.ImageField(max_length=256, upload_to='')),
                ('city', models.CharField(max_length=126)),
                ('desc', models.TextField()),
                ('state', models.CharField(max_length=126)),
                ('isdeleted', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=126)),
                ('password', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=126)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField(max_length=126)),
            ],
        ),
    ]
